### ISSUE TITLE
Installing on CentOS

### ISSUE THREAD

**Issue by akfourth** [barricklab/breseq#182]
I am trying to install breseq system-wide on CentOS 7. I have updated the gcc to gcc-8.2.0. So if I write
gcc --version
the output is:
gcc (GCC) 8.2.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

However, when I do 
make 
OR
sudo make
while trying to install breseq, it gives an error saying 
In file included from ./libbreseq/storable.h:25:0,
                 from ./libbreseq/settings.h:24,
                 from libbreseq/fastq.h:23,
                 from libbreseq/alignment.h:25,
                 from alignment.cpp:19:
./libbreseq/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
make[1]: *** [alignment.lo] Error 1
make[1]: Leaving directory `/Programs/breseq-0.33.1/src/c/breseq'
make: *** [all-recursive] Error 1

What can I do to fix this ? Thanks!

**Comment by akfourth** [comment]
I tried to do this, and it still gave the same error. Perhaps this is something CentOS-specific? Any other suggestions would be welcome.

**Comment by alexmyczko** [comment]
also builds with debian, gcc (Debian 8.2.0-17) 8.2.1 20190204

**Comment by akfourth** [comment]
Just a follow-up. I could never get this to work as is on my CentOS system. It might be something specific to my system, since the old gcc version (4.8.5) and the new version (8.2.0) did not install in the same location, and it is possible that the breseq might have been attempting to use the older version. 

However, I think I've found a workaround for now at least by changing a parameter in the /breseq-0.33.1/src/c/breseq/libbreseq/json.hpp file:

In this part of the file - 

// exclude unsupported compilers
#if defined(__clang__)
    #if (__clang_major__ * 10000 + __clang_minor__ * 100 + __clang_patchlevel__) < 30400
        #error "unsupported Clang version - see https://github.com/nlohmann/json#supported-compilers"
    #endif
#elif defined(__GNUC__)
    #if (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC_PATCHLEVEL__) < 40900

In the last line, I changed the 40900 to 0 and that seems to work for now. 

I hope it won't affect the breseq results in any way. 

Thanks !!

**Comment by jeffreybarrick** [comment]
Thanks for posting this workaround!

This part of the source code is only for generating JSON style output files containing the run settings and predictions, so it should not affect _breseq_'s normal function.
